import UIKit

extension UIColor {
    static let neutral0 = UIColor(named: "Neutral0")
    static let neutral10 = UIColor(named: "Neutral10")
    static let neutral20 = UIColor(named: "Neutral20")
    static let neutral30 = UIColor(named: "Neutral30")
    static let neutral40 = UIColor(named: "Neutral40")
    static let neutral50 = UIColor(named: "Neutral50")
    static let neutral60 = UIColor(named: "Neutral60")
    static let neutral70 = UIColor(named: "Neutral70")
    static let neutral80 = UIColor(named: "Neutral80")
    static let neutral90 = UIColor(named: "Neutral90")
    static let neutral100 = UIColor(named: "Neutral100")
    static let primary0 = UIColor(named: "Primary0")
    static let primary10 = UIColor(named: "Primary10")
    static let primary20 = UIColor(named: "Primary20")
    static let primary30 = UIColor(named: "Primary30")
    static let primary40 = UIColor(named: "Primary40")
    static let primary50 = UIColor(named: "Primary50")
    static let primary60 = UIColor(named: "Primary60")
    static let primary70 = UIColor(named: "Primary70")
    static let primary80 = UIColor(named: "Primary80")
    static let primary90 = UIColor(named: "Primary90")
    static let primary100 = UIColor(named: "Primary100")
    static let secondary0 = UIColor(named: "Secondary0")
    static let secondary10 = UIColor(named: "Secondary10")
    static let secondary20 = UIColor(named: "Secondary20")
    static let secondary30 = UIColor(named: "Secondary30")
    static let secondary40 = UIColor(named: "Secondary40")
    static let secondary50 = UIColor(named: "Secondary50")
    static let secondary60 = UIColor(named: "Secondary60")
    static let secondary70 = UIColor(named: "Secondary70")
    static let secondary80 = UIColor(named: "Secondary80")
    static let secondary90 = UIColor(named: "Secondary90")
    static let secondary100 = UIColor(named: "Secondary100")
    static let rating = UIColor(named: "Rating")
    static let error10 = UIColor(named: "Error10")
    static let error100 = UIColor(named: "Error100")
    static let success10 = UIColor(named: "Success10")
    static let success100 = UIColor(named: "Success100")
}
